# values.yaml

# Replica count for the vector deployment
replicaCount: 1

# Image details
image:
  repository: viewio/view-vector
  tag: v1.1.0
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 8311

# Environment variables
env:
  VIEW_ACCOUNT_GUID: '00000000-0000-0000-0000-000000000000'
  VIEW_DATABASE_TYPE: Mysql
  VIEW_DATABASE_HOST: mysql
  VIEW_DATABASE_PORT: 3306
  VIEW_DATABASE_NAME: view
  VIEW_DATABASE_USER: root
  VIEW_DATABASE_FILE: view.db
  VIEW_DATABASE_PASS: password
  VIEW_CONSOLE_LOGGING: 1
  VIEW_CONTROL_HOSTNAME: control.view.io
  VIEW_CONTROL_PORT: 8403
  VIEW_CONTROL_SSL: true
  VIEW_CONTROL_SWVERSION: v1.0.0
  TERM: 'xterm-256color'

# Persistent Volume Claim configuration
pvc:
  enabled: true
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: 1Gi
